### ISSUE TITLE
Oh wow you have to change the name.

### ISSUE THREAD

**Issue by skorokithakis** [parro-it/canibekikked#2]
I suggest canibekikked. As I understand it, "kike" is to jews what "nigger" is to black people.

**Comment by egroat** [comment]
That is a ridiculous level of attempted political correctness, and works counter to preventing words like kike or nigger from having negative connotations. 

If anyone wants to claim being offended by this totally unrelated usage of letters arranged in the same order then they are simply ensuring they can be offended in the future. 

CanIBeKiked / canibekiked is fine.

**Comment by wodim** [comment]
According to the definition in Urban Dictionary, I think "kiked" is appropriate: https://www.urbandictionary.com/define.php?term=Kiked

**Comment by skorokithakis** [comment]
"Appropriate" as in "wow so inappropriate", you mean?

**Comment by skorokithakis** [comment]
Also, the correct past tense of "kik" is "kikked". Because it's pronounced "kick", not "kike".

**Comment by wodim** [comment]
Please, look at my avatar. Of course I think it's appropriate.

**Comment by skorokithakis** [comment]
Oh, I couldn't make out the letters before. Or know what Trump stands for, but I'm guessing from the context that he's big on racism.

**Comment by ghost** [comment]
Is 'please look at my avatar' the new 'please clap' ?

**Comment by pavellishin** [comment]
> That is a ridiculous level of attempted political correctness, and works counter to preventing words like kike or nigger from having negative connotations.

Insensitivity to the fact that those words _do_ have negative connotations, and will for many more years does not advance anything positive.

> If anyone wants to claim being offended by this totally unrelated usage of letters arranged in the same order then they are simply ensuring they can be offended in the future.

That sounds like you're suggesting that the problem lies entirely with those offended - you're effectively victim-blaming.

This isn't just pointless political correctness. It's basic sensitivity to the fact that _words mean things_.

**Comment by egroat** [comment]
There are no victims here.  The application does not do anything negative for anybody,  the naming is coincidental and if anyone was to attempt to be offended the barest bit of context would suffice to stifle it.

**Comment by wodim** [comment]
There should be a github reaction called "oy vey another shoah". 

Well, I am UNSUBBING from this thread of butthurt individuals. Sorry guys.

**Comment by skorokithakis** [comment]
@egroat I kinda understand your viewpoint as well, but what gets me is that "kiked" is the past tense of "kike", not of "kik".

**Comment by egroat** [comment]
@skorokithakis ok I can see that.  I still think its an overreaction but couched as it is with the semi-justification as a correction,  there is reason for a renaming.

**Comment by ryanbreen** [comment]
If you consider the fact that "can I be jewed" would be an anti-semtic way to say "can I be cheated," it's possible for a reasonable person to think "can I be kiked" is an intentional double entendre with this name. I agree this really needs to be changed.

**Comment by Incognito** [comment]
A few years ago my Hungarian grandmother died. In Hungarian there's a word for "wooden" which sounds like "fuh". And a lot of words starting with a " k" sound.

One of my favorite childhood pasttimes was coming up with words like "wooden duck" (fuh kah cha) or wooden car (fuh kar ay) or wooden spoon (fuh ka nal).

Oh how I laughed and laughed at how unrelated things sounded hilarious in English. But the moral of this story is that Hungarians should change their language to protect those who only hear the imagined English that was never really there.

**Comment by Gargron** [comment]
Kik is pronounced like "kick". "Kiked" does not contain the pronounciation of "kick", but does contain the pronounciation of "kike", which is an ethnic slur. Probably a mistake by someone who isn't a native English speaker, but it could be taken as an attempted double entendre.

Also regarding the comment above mine, "can I be" is English, not Hungarian. The name/phrase is intended to be read like an English sentence.

Edit: Seems like the comment above mine was removed. Disregard last paragraph.

**Comment by skorokithakis** [comment]
Also, the author is in for a great surprise when he sees this comment thread. @parro-it, just to put you at ease, none of us really feel very strongly about this, it's up to you.

**Comment by gyardley** [comment]
I feel strongly about it.

**Comment by tilleps** [comment]
Why not just canibekikd?

**Comment by christianbundy** [comment]
Personally, I'm not offended by the name because I don't think it was intentional -- _however_, it's unnecessarily ambiguous and controversial. I know this isn't very academic, but take a look at how the words [kiked](https://twitter.com/search?q=kiked), [kikked](https://twitter.com/search?q=kikked), and [kik'd](https://twitter.com/search?q=kik%27d) are used on Twitter.

My vote is for "kikked", which removes the confusion of potential anti-semiticism without adding an apostrophe (which doesn't work in the repo name). Either way, good project -- thanks for your work on this @parro-it.

**Comment by athomann** [comment]
Add functionality to see if your repo name has a racial slur?

**Comment by parro-it** [comment]
Hi all. I'm so sorry, I had no idea what "kike" means before reading this issue.

I'm not a native speaker, I intend the word only in the sense "to suffer the same fate as the azer/kik project".
I will rename the repository as "kikked" and add a note in readme.

**Comment by parro-it** [comment]
> Add functionality to see if your repo name has a racial slur?

I saw some day ago a repo containg a list of offensive words. 
I think it should be easy to check if a repo name is contained there.

**Comment by skorokithakis** [comment]
@parro-it No problem, I just figured I'd give you a heads up because not many people know what "kike" means unless they're native English speakers or watch South Park.

**Comment by parro-it** [comment]
@skorokithakis, thank you for the issue! I used to watch South Park, but it's translated in Italian here.

**Comment by PixnBits** [comment]
@parro-it FWIW I've never heard the term until now and I'm a native English speaker. Might be regional? If you find that repo with a list of words to avoid, could you post it here? It'd help me out, maybe others :)

**Comment by parro-it** [comment]
Sure, it's https://github.com/shutterstock/List-of-Dirty-Naughty-Obscene-and-Otherwise-Bad-Words

**Comment by joshmanders** [comment]
brb going to open an issue with kik interactive claiming kik sounds like "kike".

You're all grasping for straws here. There's nothing wrong with the name. Don't make a mountain out of a molehill. Actually not even a molehill. This is the friggen plains, flat as shit. No mountains. Stop.

**Comment by christianbundy** [comment]
@joshmanders Just to be clear, you're advocating that we revert the name to a misspelling that _also_ happens to be a racial slur? Hilarious. I understand your frustration against people who want to be offended by everything, but unfortunately this is nothing more than a non-native English speaker making an innocent misspelling.

Don't believe me? Try replacing "kik" with similar verbs:
- **Beg:** "beged" or "begged"?
- **Clap:** "claped" or "clapped"?
- **Fan:** "faned" or "fanned"?
- **Whip:** "whiped" or "whipped"?

Now, let's try "kik" again:
- **Kik:** "kiked" or "kikked"? 

If you're looking for a primer on the past tense (maybe you're learning English for the first time?), [I'd highly recommend this video](https://www.youtube.com/watch?v=QlZXd-m6Pdw). There's a great example at the 2-minute mark where they go over the past tense of "stop" (which is "stopped", not "stoped").

Please let me know if there are any other questions I can answer for you regarding English, the past tense, or just general etiquette on GitHub.

**Comment by joshmanders** [comment]
@christianbundy Then we all better be outraged that GitHub, Inc, or GitLab, or any other company, including Torvalds the creator of Git change the names right now, because Git is offensive. http://www.urbandictionary.com/define.php?term=Git

**Comment by joshmanders** [comment]
Can't pick and choose what you want to be offended about. Either be full blown politically correct or stop taking so much offense to every little possible thing.

**Comment by skorokithakis** [comment]
The difference there is that someone can't just assume the word "git" is directed at them, because "git" means "an unpleasant or contemptible person". "Kike" is offensive to any jew. I'm as much against political correctness as the next guy, but, since a repo rename is just one setting away, I don't see what's so bad about this. It's like someone naming their repo "canibeniggered" (completely by accident) and people being outraged at other people's soft suggestion that it perhaps be renamed.

I didn't strong-arm anyone into it or even express any strong preference, and @parro-it was gracious enough to rename it when he became aware of the issue, so I don't think this is the particular hill to fight the anti-PC battle on...

**Comment by joshmanders** [comment]
30+ comments of people being outraged by something that shouldn't have any outrage around it. When applied to the context in which this module was made, there is no reason one should even think about "kike". It's those who read into it wrong who are blowing it up.

How about we do more productive things. The JavaScript ecosystem is too entangled with being politically correct about every single little aspect of it, that I don't even know if anyone actually does anything outside of scour code to find something to be offended and outraged about.

**Comment by christianbundy** [comment]
@joshmanders I've previously expressed that I'm not offended by the name, but at least now there's no doubt as to whether you read the discussion. My vote to change the name came from the fact that it's incorrectly spelled, just as I would do if the name said "stoped" instead of "stopped".

**The only reason you want to revert to the incorrect spelling is that you're offended that other people are offended by "kike", and want to make a point of keeping the racial slur to stick it to "politically correct" people.**

If [`node-gyp`](https://github.com/nodejs/node-gyp) took over [`gyp`](https://www.npmjs.com/package/gyp) and some project named `can-i-be-gypped` changed its name to avoid using "[gypped](http://www.urbandictionary.com/define.php?term=gypped)", then your comments might be relevant. Unfortunately for you, that isn't what happened. Instead, there was a misspelling in the project name, and it ended up being a racial slur by coincidence. You're making the claim that we should keep this misspelling just to maintain the racial slur. Classy.

Why are you still commenting? You've already demonstrated:
- You didn't read the previous discussion.
- You aren't offended by "kike".
- If anyone is offended by something you aren't, they're "politically correct".
- You're offended by "politically correct people". (?!?!)
- The things that offend you are the only things that are offensive, everything else is just "making a mountain out of friggen plains, flat as shit".
- You want to purposefully butcher the English language just so that you can offend the "politically correct" people with racial slurs.

I don't know which holy war you think you're fighting, but you aren't going to win it by misspelling words to create racial slurs (however if that _were_ a game, I'd call it "Donald Trump Scrabble").

**Comment by joshmanders** [comment]
If you're going to use the misspelling as your basis for changing it, then just say that. But alas, most of the comments here are about it being a racial slur.

I'm not fighting any holy war, I'm just expressing my deep disgust with this ecosystems vast desire to remove anything that could offend anyone for any little thing, all while using something that is widely known as being an offensive slur. But that don't matter apparently. Hypocrisy is the war I am fighting.

**Comment by pavellishin** [comment]
> 30+ comments of people being outraged by something that shouldn't have any outrage around it.

Nobody is actually outraged. We're merely capable of seeing things from perspectives other than our own.

> How about we do more productive things. The JavaScript ecosystem is too entangled with being politically correct about every single little aspect of it, that I don't even know if anyone actually does anything outside of scour code to find something to be offended and outraged about.

And you're meta-outraged at this, being whatever the opposite of politically correct is, instead of actually doing anything outside of scouring comments to find something to be offended about.

And for what it's worth, `gyp` is also questionable, but so are a billion things. Just because someone is choosing to comment on X, but not on Y, doesn't make their comments on X irrelevant or hypocritical. In fact, the only reason some of us are commenting _here_ and not _elsewhere_ is because we're _not_ on some PC crusade - we just happened to notice something and _suggested a way to improve something in the Javascript ecosystem_.

**Comment by joshmanders** [comment]
> This isn't just pointless political correctness. It's basic sensitivity to the fact that words mean things.

Let me preface this with while I think the name of this module was fine how it was, I don't advocate calling anyone an N word, or a kike, but you're 100% right on what you said _words mean things_. They meant many things long before their negative forms became something. Just like the swastika meant peace before Nazi germany. The N word is derived from how it was pronounced/said in Latin, and Kike came from the Yiddish word kikel which meant "circle" for which is how Jewish immigrants signed on Ellis Island.

It's when used in a certain context that it goes from being used in it's correct and original form, to being used in a negative form.

**Comment by pavellishin** [comment]
> It's when used in a certain context that it goes from being used in it's correct and original form, to being used in a negative form.

Unfortunately, history weighs words down with meaning even when they're used in a neutral context. Come on - you didn't even write "nigger", choosing instead "N word". From context, it would be 100% obvious that you wouldn't be using it to be offensive, but the word is still, in 2016, weighed down so heavily with connotation that it's hard to type, to see, to read.

**Comment by joshmanders** [comment]
> From context, it would be 100% obvious that you wouldn't be using it to be offensive, but the word is still, in 2016, weighed down so heavily with connotation that it's hard to type, to see, to read.

Exactly, "nigger" is used way more in society than "kike" is, that's why I have a hard time typing it and resort to the "N word". Looks I'm not going against you guys on the term being offensive. I'm going against the fact that in such a context, people are making a scruff out of it BEING offensive. @christianbundy I apologize to you because after going back and rereading again (read this thread on and off over the day or so because of events away from computer keeping me) I see you were fighting for the correct spelling.

It bothers me heavily how much people are finding anything they can to be offended about. And it's always the ones who have no reason to be offended who are offended. Why? Why are people that way? Then they're only offended about what's higher profile offensive. As if someone somewhere is holding them hostage and forcing them to be offended or some skeleton is going to be let out of the closet and that can't happen.

Why are white people being offended by someone saying the N word? But every black person I've talked to seriously about this (including many close personal friends) say it doesn't bother them?

Why are non-Jewish people being offended by a non-native English speaker misspelling a word and the resulting sequence when pronounced incorrectly is a slur?

Why is it okay for all these overly offended but shouldn't have a reason to be offended people get to express their offense to such things, yet someone who's sick of seeing the constant "OMG THAT'S OFFENSIVE TO SOMEONE SOMEWHERE PROBABLY SO YOU SHOULD SPEND 600 HOURS CAREFULLY CRAFTING YOUR 3 WORD SENTENCE INCASE SOMEONE IS OFFENDED BY LONG WORDS!" but I can't express my offense to people being offended so much?

**Comment by joshmanders** [comment]
I'm grumpy, I apologize to everyone. Have a good Sunday evening.

**Comment by christianbundy** [comment]
@joshmanders You're good, man. I understand where you're coming from -- even if I disagree on this specific issue. Thought you might like [this](https://www.youtube.com/watch?v=fHMoDt3nSHs). Have a kickass night Josh.

**Comment by PixnBits** [comment]
FWIW "git" refers to Torvalds himself:

> Torvalds quipped about the name git...: "I'm an egotistical bastard, and I name all my projects after myself. First 'Linux', now 'git'."

https://en.wikipedia.org/wiki/Git_(software)#History

**Comment by shotxxxx** [comment]
kikked? You got cucked, cuck.

**Comment by rr-** [comment]
@skorokithakis what about https://github.com/skorokithakis/expounder/ ? Ex pounder? I think we've seen lighter names being targeted.

I wish this sort of issues was reported by people that were actually offended rather than those thinking someone else might.

**Comment by christianbundy** [comment]
@rr- Please just let this issue die. Go write a blog post or something productive, but don't waste our time harassing people on a closed issue that has nothing to do with you. Comments like yours are the reason that issues get locked.

I need coffee.

**Comment by pavellishin** [comment]
> I wish this sort of issues was reported by people that were actually offended rather than those thinking someone else might

Isn't this the equivalent of saying that bugs should only be reported in production once they affect someone?

**Comment by skorokithakis** [comment]
@rr- Expounder was intentional, that lib just likes to pound all your exes.

**Comment by skorokithakis** [comment]
@pavellishin Eh, it's more like saying "this isn't a bug unless someone minds the behaviour", which I kind of agree with. In any case, this has become a much larger issue than I intended, so can we just drop it, like @christianbundy said?

Plus, none of you cottoned on to my real agenda, which is that I'm a prescriptivist and hated the malformed past tense.

**Comment by OBAMATRON** [comment]
What if you just change it to "canibejewed"?
